#!/usr/bin/env node



var program = require('commander');

program
  .version('0.0.1')
  .option('-h --hot ', "it's hot")
  .option('-c, --cold', "it's cold")
  .option('-d, --dry', "it's clear")
  .option('-w, --wet [type]', 'Add the specified type of precipitation [rain]')
  .parse(process.argv);

console.log('outside it is:');




if(program.cold && program.wet) console.log('-snowing'); 
else if(program.hot && program.dry) console.log('-sunny');
 else if(program.hot) console.log('  - hot');
 else if (program.cold) console.log('  - cold');
 else if (program.wet) console.log('  - wet');
 else if (program.dry) console.log('-dry');

